### ISSUE TITLE
Some compilation issues how-to

### ISSUE THREAD

**Issue by rifux** [YumeMichi/kernel_xiaomi_pipa#1]
#### *Hello!*

Can I ask you what defconfigs should I use to compile this kernel? Is it a GKI kernel?

**Comment by YumeMichi** [comment]
Check the build script.
https://github.com/YumeMichi/kernel_xiaomi_pipa/blob/clang-lto/build.sh

**Comment by rifux** [comment]
> Check the build script. https://github.com/YumeMichi/kernel_xiaomi_pipa/blob/clang-lto/build.sh

Thanks for help! Kernel was built successfully.
