### ISSUE TITLE
Broken RIL

### ISSUE THREAD

**Issue by amackpro** [YumeMichi/kernel_xiaomi_pipa#2]
i was trying to build your kernel for munch 
have fixed most issues but got into Broken RIL i checked if mdm was disabled in dts but it wasnt .
https://github.com/amackpro/android_kernel_xiaomi_sm8250/commits/new/

please look onto it.

**Comment by YumeMichi** [comment]
you properly need to pick other phone stuff from lineageos

**Comment by amackdev** [comment]
> you properly need to pick other phone stuff from lineageos

what u mean , send a commit as example , cuz only RIL is broken in ur kernel for me
